name: run tests
on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          cache: 'pip'

      - name: install dependencies and code with black
        run: |
         sudo apt-get update
         sudo apt-get install xvfb
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         black --include="\.py" --exclude="env/*" .

      - name: lint code
        run: ruff . --ignore E402,E501

      - name: Check for changes
        id: check_changes
        run: |
         git diff --exit-code --quiet || echo "changes=true" >> $GITHUB_STATE
         echo "changes=false" >> $GITHUB_STATE
      
      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
         git config --global user.name ${{ github.actor }}
         git config --global user.email ${{ github.actor }}@users.noreply.github.com
         git add .
         git commit -m "Format code with black"
         git push origin ${{ github.ref }}

      - name: run tests
        run: xvfb-run -a python tests/test_swimming.py
